/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leonardo
 */
public class MinhasPerguntas extends javax.swing.JFrame {
    
    private void carregarPerguntas() {
    try {
        DAO dao = new DAO();
        java.util.ArrayList<Pergunta> perguntas = dao.listarPerguntas();

        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblPerguntas.getModel();

        modelo.setRowCount(0);

        for (Pergunta pergunta : perguntas) {
            modelo.addRow(new Object[]{
                pergunta.getId(),
                pergunta.getEnunciado(),
                pergunta.getNivel(),
                pergunta.getRespostaCorreta()
            });
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar perguntas.");
        e.printStackTrace();
    }
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MinhasPerguntas.class.getName());

    /**
     * Creates new form MinhasPerguntas
     */
    public MinhasPerguntas() {
    initComponents();

    getContentPane().setLayout(null);

    jPanel1.setBounds(0, 0, 760, 350);
    jScrollPane1.setBounds(40, 350, 680, 230);

    setSize(760, 640);
    setLocationRelativeTo(null);
    setResizable(false);

    carregarPerguntas();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloMinhasPerguntas = new javax.swing.JLabel();
        lblSubtituloMinhasPerguntas = new javax.swing.JLabel();
        btnExcluirPergunta = new javax.swing.JButton();
        btnNovaPergunta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerguntas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloMinhasPerguntas.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloMinhasPerguntas.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        lblTituloMinhasPerguntas.setForeground(new java.awt.Color(39, 51, 54));
        lblTituloMinhasPerguntas.setText("MINHAS PERGUNTAS");

        lblSubtituloMinhasPerguntas.setBackground(new java.awt.Color(255, 255, 255));
        lblSubtituloMinhasPerguntas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblSubtituloMinhasPerguntas.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloMinhasPerguntas.setText("Gerencie e visualize as perguntas cadastradas.");

        btnExcluirPergunta.setBackground(new java.awt.Color(255, 51, 51));
        btnExcluirPergunta.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnExcluirPergunta.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirPergunta.setText("Excluir");
        btnExcluirPergunta.addActionListener(this::btnExcluirPerguntaActionPerformed);

        btnNovaPergunta.setBackground(new java.awt.Color(39, 51, 54));
        btnNovaPergunta.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNovaPergunta.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaPergunta.setText("NOVA PERGUNTA");
        btnNovaPergunta.addActionListener(this::btnNovaPerguntaActionPerformed);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo etec.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO LAB QUIZ.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO CPS.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        btnVoltar1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnVoltar1.setForeground(new java.awt.Color(39, 51, 54));
        btnVoltar1.setText("VOLTAR");
        btnVoltar1.addActionListener(this::btnVoltar1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloMinhasPerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(lblSubtituloMinhasPerguntas))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnNovaPergunta)
                            .addGap(18, 18, 18)
                            .addComponent(btnVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnExcluirPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblTituloMinhasPerguntas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSubtituloMinhasPerguntas)
                        .addGap(0, 145, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovaPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirPergunta)
                            .addComponent(btnVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblPerguntas.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        tblPerguntas.setForeground(new java.awt.Color(39, 51, 54));
        tblPerguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Enunciado ", "Nível ", "Resposta correta"
            }
        ));
        tblPerguntas.setGridColor(new java.awt.Color(220, 220, 220));
        tblPerguntas.setRowHeight(28);
        tblPerguntas.setSelectionBackground(new java.awt.Color(39, 51, 54));
        tblPerguntas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblPerguntas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(1279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPerguntaActionPerformed
TelaQuestaoProfessor tela = new TelaQuestaoProfessor();
tela.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovaPerguntaActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
LoginProfessor tela = new LoginProfessor();
tela.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void btnExcluirPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPerguntaActionPerformed
int linhaSelecionada = tblPerguntas.getSelectedRow();

if (linhaSelecionada == -1) {
    javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma pergunta para excluir.");
    return;
}

int confirmacao = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Tem certeza que deseja excluir esta pergunta?",
        "Confirmar exclusão",
        javax.swing.JOptionPane.YES_NO_OPTION
);

if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
    try {
        int id = Integer.parseInt(tblPerguntas.getValueAt(linhaSelecionada, 0).toString());

        DAO dao = new DAO();
        dao.excluirPergunta(id);

        javax.swing.JOptionPane.showMessageDialog(this, "Pergunta excluída com sucesso!");

        carregarPerguntas();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir pergunta.");
        e.printStackTrace();
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirPerguntaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MinhasPerguntas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirPergunta;
    private javax.swing.JButton btnNovaPergunta;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubtituloMinhasPerguntas;
    private javax.swing.JLabel lblTituloMinhasPerguntas;
    private javax.swing.JTable tblPerguntas;
    // End of variables declaration//GEN-END:variables
}
