/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leonardo
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());
    private String perfilSelecionado = "aluno";

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
    initComponents();

    setContentPane(jpnlPrincipal);
    pack();
    setLocationRelativeTo(null);
    setResizable(false);

    BtnSoualuno.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    BtnSouprofessor.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    btnEntrar.setUI(new javax.swing.plaf.basic.BasicButtonUI());

    BtnSoualuno.setBackground(new java.awt.Color(39, 51, 54));
    BtnSoualuno.setForeground(new java.awt.Color(255, 255, 255));

    BtnSouprofessor.setBackground(new java.awt.Color(255, 255, 255));
    BtnSouprofessor.setForeground(new java.awt.Color(39, 51, 54));

    btnEntrar.setBackground(new java.awt.Color(39, 51, 54));
    btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jpnlPrincipal = new javax.swing.JPanel();
        BtnSouprofessor = new javax.swing.JButton();
        TxtUsuario = new javax.swing.JLabel();
        TextoUsuario = new javax.swing.JTextField();
        jsenha = new javax.swing.JLabel();
        TextoSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        AcesseOsistematitulo = new javax.swing.JTextField();
        jpnlTopo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SubtituloAcesse = new javax.swing.JTextField();
        BtnSoualuno = new javax.swing.JButton();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO CPS.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        BtnSouprofessor.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnSouprofessor.setForeground(new java.awt.Color(39, 51, 54));
        BtnSouprofessor.setText(" Professor");
        BtnSouprofessor.addActionListener(this::BtnSouprofessorActionPerformed);

        TxtUsuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        TxtUsuario.setText("Usuário");

        TextoUsuario.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        TextoUsuario.addActionListener(this::TextoUsuarioActionPerformed);

        jsenha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jsenha.setForeground(new java.awt.Color(39, 51, 54));
        jsenha.setText("Senha");

        TextoSenha.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        TextoSenha.addActionListener(this::TextoSenhaActionPerformed);

        btnEntrar.setBackground(new java.awt.Color(39, 51, 54));
        btnEntrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.addActionListener(this::btnEntrarActionPerformed);

        AcesseOsistematitulo.setFont(new java.awt.Font("Verdana", 1, 26)); // NOI18N
        AcesseOsistematitulo.setForeground(new java.awt.Color(39, 51, 54));
        AcesseOsistematitulo.setText("ACESSE O SISTEMA");
        AcesseOsistematitulo.setBorder(null);
        AcesseOsistematitulo.addActionListener(this::AcesseOsistematituloActionPerformed);

        jpnlTopo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO CPS.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo etec.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO LAB QUIZ.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jpnlTopoLayout = new javax.swing.GroupLayout(jpnlTopo);
        jpnlTopo.setLayout(jpnlTopoLayout);
        jpnlTopoLayout.setHorizontalGroup(
            jpnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlTopoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jpnlTopoLayout.setVerticalGroup(
            jpnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SubtituloAcesse.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        SubtituloAcesse.setText("Selecione seu perfil e faça o login!");
        SubtituloAcesse.setBorder(null);
        SubtituloAcesse.addActionListener(this::SubtituloAcesseActionPerformed);

        BtnSoualuno.setBackground(new java.awt.Color(39, 51, 54));
        BtnSoualuno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnSoualuno.setForeground(new java.awt.Color(255, 255, 255));
        BtnSoualuno.setText("Aluno");
        BtnSoualuno.addActionListener(this::BtnSoualunoActionPerformed);

        javax.swing.GroupLayout jpnlPrincipalLayout = new javax.swing.GroupLayout(jpnlPrincipal);
        jpnlPrincipal.setLayout(jpnlPrincipalLayout);
        jpnlPrincipalLayout.setHorizontalGroup(
            jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlTopo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtUsuario)
                            .addComponent(jsenha)
                            .addComponent(TextoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlPrincipalLayout.createSequentialGroup()
                                .addComponent(BtnSoualuno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnSouprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlPrincipalLayout.createSequentialGroup()
                        .addComponent(AcesseOsistematitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlPrincipalLayout.createSequentialGroup()
                        .addComponent(SubtituloAcesse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))))
        );
        jpnlPrincipalLayout.setVerticalGroup(
            jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(AcesseOsistematitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubtituloAcesse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSouprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSoualuno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1487, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(623, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSouprofessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSouprofessorActionPerformed
perfilSelecionado = "professor";

BtnSouprofessor.setBackground(new java.awt.Color(39, 51, 54));
BtnSouprofessor.setForeground(new java.awt.Color(255, 255, 255));

BtnSoualuno.setBackground(new java.awt.Color(255, 255, 255));
BtnSoualuno.setForeground(new java.awt.Color(39, 51, 54));        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSouprofessorActionPerformed

    private void TextoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoUsuarioActionPerformed

    private void TextoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoSenhaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
try {
    String usuarioDigitado = TextoUsuario.getText();
    String senhaDigitada = String.valueOf(TextoSenha.getPassword());

    DAO dao = new DAO();
    Usuario usuario = dao.buscarUsuario(usuarioDigitado, senhaDigitada, perfilSelecionado);

    if (usuario != null) {
        Sessao.usuarioLogado = usuario;

        javax.swing.JOptionPane.showMessageDialog(this, "Bem-vindo, " + usuario.getNome() + "!");

        if (usuario.getTipo().equals("aluno")) {
            TelaAluno tela = new TelaAluno();
            tela.setVisible(true);
            this.dispose();

        } else if (usuario.getTipo().equals("professor")) {
            LoginProfessor tela = new LoginProfessor();
            tela.setVisible(true);
            this.dispose();
        }

    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos.");
    }

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro ao fazer login.");
    e.printStackTrace();
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void AcesseOsistematituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcesseOsistematituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcesseOsistematituloActionPerformed

    private void SubtituloAcesseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtituloAcesseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubtituloAcesseActionPerformed

    private void BtnSoualunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSoualunoActionPerformed
perfilSelecionado = "aluno";

BtnSoualuno.setBackground(new java.awt.Color(39, 51, 54));
BtnSoualuno.setForeground(new java.awt.Color(255, 255, 255));

BtnSouprofessor.setBackground(new java.awt.Color(255, 255, 255));
BtnSouprofessor.setForeground(new java.awt.Color(39, 51, 54));        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSoualunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AcesseOsistematitulo;
    private javax.swing.JButton BtnSoualuno;
    private javax.swing.JButton BtnSouprofessor;
    private javax.swing.JTextField SubtituloAcesse;
    private javax.swing.JPasswordField TextoSenha;
    private javax.swing.JTextField TextoUsuario;
    private javax.swing.JLabel TxtUsuario;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jpnlPrincipal;
    private javax.swing.JPanel jpnlTopo;
    private javax.swing.JLabel jsenha;
    // End of variables declaration//GEN-END:variables
}

