/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Leonardo
 */
public class TelaCadastrarAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrarAluno
     */
    public TelaCadastrarAluno() {
    initComponents();

    setContentPane(jpnPrincipal);
    pack();
    setLocationRelativeTo(null);
    setResizable(false);

    txtNomeAluno.setText("");
    txtUsuarioAluno.setText("");
    txtSenhaAluno.setText("");
    txtConfirmarSenhaAluno.setText("");

    btnCadastrarAluno.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    btnCadastrarAluno.setBackground(new java.awt.Color(39, 51, 54));
    btnCadastrarAluno.setForeground(new java.awt.Color(255, 255, 255));
    btnCadastrarAluno.setFocusPainted(false);
    btnCadastrarAluno.setOpaque(true);

    btnVoltar.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
    btnVoltar.setForeground(new java.awt.Color(39, 51, 54));
    btnVoltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 51, 54), 1));
    btnVoltar.setFocusPainted(false);
    btnVoltar.setOpaque(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        txtUsuarioAluno = new javax.swing.JTextField();
        txtSenhaAluno = new javax.swing.JPasswordField();
        txtConfirmarSenhaAluno = new javax.swing.JPasswordField();
        btnCadastrarAluno = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblNomeAluno = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSenhaAluno = new javax.swing.JLabel();
        lblConfirmarSenhaAluno = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();

        jpnPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO LAB QUIZ.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO CPS.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo etec.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        txtNomeAluno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtNomeAluno.setText("jTextField1");

        txtUsuarioAluno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtUsuarioAluno.setText("jTextField1");

        txtSenhaAluno.setText("jPasswordField1");

        txtConfirmarSenhaAluno.setText("jPasswordField1");

        btnCadastrarAluno.setBackground(new java.awt.Color(39, 51, 54));
        btnCadastrarAluno.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCadastrarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarAluno.setText("CADASTRAR ALUNO");
        btnCadastrarAluno.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(39, 51, 54)));
        btnCadastrarAluno.addActionListener(this::btnCadastrarAlunoActionPerformed);

        btnVoltar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(39, 51, 54));
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(39, 51, 54)));
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        lblNomeAluno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblNomeAluno.setText("Nome do aluno");

        lblUsuario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblUsuario.setText("Usuário");

        lblSenhaAluno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblSenhaAluno.setText("Senha");

        lblConfirmarSenhaAluno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblConfirmarSenhaAluno.setText("Confirmar Senha");

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 26)); // NOI18N
        lblTitulo.setText("CADASTRAR ALUNO");

        lblSubtitulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblSubtitulo.setText("Crie o acesso do aluno ao quiz.");

        javax.swing.GroupLayout jpnPrincipalLayout = new javax.swing.GroupLayout(jpnPrincipal);
        jpnPrincipal.setLayout(jpnPrincipalLayout);
        jpnPrincipalLayout.setHorizontalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addComponent(btnCadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNomeAluno)
                        .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtConfirmarSenhaAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(txtSenhaAluno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuarioAluno, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(lblSenhaAluno)
                        .addComponent(lblConfirmarSenhaAluno)
                        .addComponent(lblUsuario)))
                .addGap(174, 174, 174))
            .addGroup(jpnPrincipalLayout.createSequentialGroup()
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(lblTitulo))
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(lblSubtitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnPrincipalLayout.setVerticalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addGap(32, 32, 32)
                .addComponent(lblNomeAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblSenhaAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConfirmarSenhaAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmarSenhaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlunoActionPerformed
        
 try {
    String nome = txtNomeAluno.getText();
    String usuarioDigitado = txtUsuarioAluno.getText();
    String senha = String.valueOf(txtSenhaAluno.getPassword());
    String confirmarSenha = String.valueOf(txtConfirmarSenhaAluno.getPassword());

    if (nome.isEmpty() || usuarioDigitado.isEmpty() || senha.isEmpty() || confirmarSenha.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
        return;
    }

    if (!senha.equals(confirmarSenha)) {
        javax.swing.JOptionPane.showMessageDialog(this, "As senhas não são iguais.");
        return;
    }

    DAO dao = new DAO();

    if (dao.usuarioExiste(usuarioDigitado)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Este usuário já existe. Escolha outro nome de usuário.");
        return;
    }

    Usuario aluno = new Usuario();
    aluno.setNome(nome);
    aluno.setUsuario(usuarioDigitado);
    aluno.setSenha(senha);
    aluno.setTipo("aluno");

    dao.cadastrarUsuario(aluno);

    javax.swing.JOptionPane.showMessageDialog(this, "Aluno cadastrado com sucesso!");

    txtNomeAluno.setText("");
    txtUsuarioAluno.setText("");
    txtSenhaAluno.setText("");
    txtConfirmarSenhaAluno.setText("");

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro ao cadastrar aluno.");
    e.printStackTrace();
}// TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarAlunoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
LoginProfessor tela = new LoginProfessor();
tela.setVisible(true);
this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAluno;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpnPrincipal;
    private javax.swing.JLabel lblConfirmarSenhaAluno;
    private javax.swing.JLabel lblNomeAluno;
    private javax.swing.JLabel lblSenhaAluno;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtConfirmarSenhaAluno;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JPasswordField txtSenhaAluno;
    private javax.swing.JTextField txtUsuarioAluno;
    // End of variables declaration//GEN-END:variables
}
