/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leonardo
 */
public class TelaAluno extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAluno.class.getName());

    /**
     * Creates new form TelaAluno
     */
    public TelaAluno() {
    initComponents();

    setContentPane(jPanel3);
    setSize(640, 520);
    setLocationRelativeTo(null);
    setResizable(false);

    // INICIAR QUIZ - botão escuro
    btnIniciarQuiz.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    btnIniciarQuiz.setBackground(new java.awt.Color(39, 51, 54));
    btnIniciarQuiz.setForeground(java.awt.Color.WHITE);
    btnIniciarQuiz.setFocusPainted(false);
    btnIniciarQuiz.setBorderPainted(false);
    btnIniciarQuiz.setOpaque(true);

    // VER RANKING - botão branco/cinza sem azul
    BtnVerRanking.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    BtnVerRanking.setBackground(java.awt.Color.WHITE);
    BtnVerRanking.setForeground(new java.awt.Color(39, 51, 54));
    BtnVerRanking.setFocusPainted(false);
    BtnVerRanking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 51, 54), 1));
    BtnVerRanking.setOpaque(true);

    // SAIR - botão branco/cinza sem azul
    btnSair.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    btnSair.setBackground(java.awt.Color.WHITE);
    btnSair.setForeground(new java.awt.Color(178, 0, 0));
    btnSair.setFocusPainted(false);
    btnSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 0, 0), 1));
    btnSair.setOpaque(true);
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BtnVerRanking = new javax.swing.JButton();
        btnIniciarQuiz = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        TituloBemvindoAluno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(39, 51, 54));
        jButton2.setText("INICIAR QUIZ");
        jButton2.setBorder(null);
        jButton2.addActionListener(this::jButton2ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        BtnVerRanking.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        BtnVerRanking.setForeground(new java.awt.Color(39, 51, 54));
        BtnVerRanking.setText("VER RANKING");
        BtnVerRanking.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(39, 51, 54)));
        BtnVerRanking.addActionListener(this::BtnVerRankingActionPerformed);

        btnIniciarQuiz.setBackground(new java.awt.Color(39, 51, 54));
        btnIniciarQuiz.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnIniciarQuiz.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarQuiz.setText("INICIAR QUIZ");
        btnIniciarQuiz.setBorder(null);
        btnIniciarQuiz.addActionListener(this::btnIniciarQuizActionPerformed);

        btnSair.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(178, 0, 0));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 0, 0)));
        btnSair.addActionListener(this::btnSairActionPerformed);

        TituloBemvindoAluno.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        TituloBemvindoAluno.setForeground(new java.awt.Color(39, 51, 54));
        TituloBemvindoAluno.setText("Bem-vindo, Aluno!");
        TituloBemvindoAluno.setBorder(null);
        TituloBemvindoAluno.addActionListener(this::TituloBemvindoAlunoActionPerformed);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO LAB QUIZ.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO CPS.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo etec.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIniciarQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnVerRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(TituloBemvindoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(TituloBemvindoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIniciarQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVerRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(733, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVerRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerRankingActionPerformed
        RankingDosAlunos tela = new RankingDosAlunos("aluno");
        tela.setVisible(true);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_BtnVerRankingActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnIniciarQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarQuizActionPerformed
TelaAlunoQuestao tela = new TelaAlunoQuestao();
tela.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarQuizActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
TelaLogin tela = new TelaLogin();
tela.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void TituloBemvindoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloBemvindoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloBemvindoAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAluno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVerRanking;
    private javax.swing.JTextField TituloBemvindoAluno;
    private javax.swing.JButton btnIniciarQuiz;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
