/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leonardo
 */
public class TelaAcerto extends javax.swing.JFrame {
    
    
    
    private TelaAlunoQuestao telaQuiz;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAcerto.class.getName());

    /**
     * Creates new form TelaAcerto
     */
    public TelaAcerto() {
    initComponents();

    setContentPane(jPanel3);
    setSize(700, 520);
    setLocationRelativeTo(null);
    setResizable(false);

    btnProximaQuestao.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    btnProximaQuestao.setBackground(new java.awt.Color(39, 51, 54));
    btnProximaQuestao.setForeground(java.awt.Color.WHITE);
    btnProximaQuestao.setFocusPainted(false);
    btnProximaQuestao.setBorderPainted(false);
    btnProximaQuestao.setOpaque(true);
}

public TelaAcerto(TelaAlunoQuestao telaQuiz) {
    initComponents();

    this.telaQuiz = telaQuiz;

    setContentPane(jPanel3);
    setSize(700, 520);
    setLocationRelativeTo(null);
    setResizable(false);

    btnProximaQuestao.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    btnProximaQuestao.setBackground(new java.awt.Color(39, 51, 54));
    btnProximaQuestao.setForeground(java.awt.Color.WHITE);
    btnProximaQuestao.setFocusPainted(false);
    btnProximaQuestao.setBorderPainted(false);
    btnProximaQuestao.setOpaque(true);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAcerto = new javax.swing.JLabel();
        lblMensagemAcerto = new javax.swing.JLabel();
        btnProximaQuestao = new javax.swing.JButton();
        lblTituloRespostaCorreta = new javax.swing.JLabel();
        lblRespostaCorreta = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPONTUACAOATUAL = new javax.swing.JLabel();
        jACERTO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO LAB QUIZ.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO CPS.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo etec.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        lblAcerto.setBackground(new java.awt.Color(255, 255, 255));
        lblAcerto.setFont(new java.awt.Font("Verdana", 1, 44)); // NOI18N
        lblAcerto.setForeground(new java.awt.Color(0, 153, 51));
        lblAcerto.setText("Acertou!");
        lblAcerto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblMensagemAcerto.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblMensagemAcerto.setText("Muito bem! Você acertou!");

        btnProximaQuestao.setBackground(new java.awt.Color(39, 51, 54));
        btnProximaQuestao.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnProximaQuestao.setForeground(new java.awt.Color(255, 255, 255));
        btnProximaQuestao.setText("Próxima questão");
        btnProximaQuestao.addActionListener(this::btnProximaQuestaoActionPerformed);

        lblTituloRespostaCorreta.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTituloRespostaCorreta.setText("Resposta correta:");

        lblRespostaCorreta.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblRespostaCorreta.setForeground(new java.awt.Color(102, 255, 102));
        lblRespostaCorreta.setText("ALTERNATIVA A ");

        jLabel10.setBackground(new java.awt.Color(0, 153, 51));
        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 51));
        jLabel10.setText("+20 PONTOS");

        jPONTUACAOATUAL.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPONTUACAOATUAL.setForeground(new java.awt.Color(39, 51, 54));
        jPONTUACAOATUAL.setText("Pontuação atual: 0 pontos");

        jACERTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ACERTO.png"))); // NOI18N
        jACERTO.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAcerto)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPONTUACAOATUAL))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblTituloRespostaCorreta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRespostaCorreta))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(lblMensagemAcerto))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jACERTO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnProximaQuestao)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jACERTO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAcerto)
                .addGap(34, 34, 34)
                .addComponent(lblMensagemAcerto)
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespostaCorreta)
                    .addComponent(lblTituloRespostaCorreta))
                .addGap(30, 30, 30)
                .addComponent(btnProximaQuestao)
                .addGap(18, 18, 18)
                .addComponent(jPONTUACAOATUAL))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProximaQuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximaQuestaoActionPerformed
if (telaQuiz != null) {
    telaQuiz.continuarDepoisDoFeedback();
}

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnProximaQuestaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAcerto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProximaQuestao;
    private javax.swing.JLabel jACERTO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jPONTUACAOATUAL;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAcerto;
    private javax.swing.JLabel lblMensagemAcerto;
    private javax.swing.JLabel lblRespostaCorreta;
    private javax.swing.JLabel lblTituloRespostaCorreta;
    // End of variables declaration//GEN-END:variables
}
