/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leonardo
 */
public class TelaQuestaoProfessor extends javax.swing.JFrame {
    private String caminhoImagem = "";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaQuestaoProfessor.class.getName());
    

    /**
     * Creates new form TelaQuestaoProfessor
     */
    public TelaQuestaoProfessor() {
    initComponents();

    setContentPane(jpnPrincipal);
    pack();
    setLocationRelativeTo(null);
    setResizable(false);

    btnSalvarPergunta.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    btnSalvarPergunta.setBackground(new java.awt.Color(178, 0, 0));
    btnSalvarPergunta.setForeground(new java.awt.Color(255, 255, 255));
    btnSalvarPergunta.setFocusPainted(false);
    btnSalvarPergunta.setOpaque(true);

    btnVoltar.setUI(new javax.swing.plaf.basic.BasicButtonUI());
    btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
    btnVoltar.setForeground(new java.awt.Color(39, 51, 54));
    btnVoltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(39, 51, 54), 1));
    btnVoltar.setFocusPainted(false);
    btnVoltar.setOpaque(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnPrincipal = new javax.swing.JPanel();
        jpnlTopo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblEnunciado = new javax.swing.JLabel();
        txtEnunciado = new javax.swing.JTextField();
        btnSalvarPergunta = new javax.swing.JButton();
        txtAlternativaA = new javax.swing.JTextField();
        lblAlternativaA = new javax.swing.JLabel();
        lblAlternativaB = new javax.swing.JLabel();
        txtAlternativaB = new javax.swing.JTextField();
        lblAlternativaC = new javax.swing.JLabel();
        lblAlternativaD = new javax.swing.JLabel();
        txtAlternativaC = new javax.swing.JTextField();
        txtAlternativaD = new javax.swing.JTextField();
        lblNivel = new javax.swing.JLabel();
        cmbNivel = new javax.swing.JComboBox<>();
        cmbRespostaCorreta = new javax.swing.JComboBox<>();
        lblRespostaCorreta = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();
        btnSelecionarImagem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDica = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jpnlTopo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO CPS.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo etec.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO LAB QUIZ.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        lblEnunciado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblEnunciado.setText("Enunciado da questão ");

        javax.swing.GroupLayout jpnlTopoLayout = new javax.swing.GroupLayout(jpnlTopo);
        jpnlTopo.setLayout(jpnlTopoLayout);
        jpnlTopoLayout.setHorizontalGroup(
            jpnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlTopoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpnlTopoLayout.createSequentialGroup()
                .addGroup(jpnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnunciado)
                    .addComponent(txtEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnlTopoLayout.setVerticalGroup(
            jpnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEnunciado, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
        );

        btnSalvarPergunta.setBackground(new java.awt.Color(153, 0, 0));
        btnSalvarPergunta.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSalvarPergunta.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarPergunta.setText("SALVAR PERGUNTA");
        btnSalvarPergunta.setToolTipText("");
        btnSalvarPergunta.addActionListener(this::btnSalvarPerguntaActionPerformed);

        txtAlternativaA.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblAlternativaA.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblAlternativaA.setText("Alternativa A:");

        lblAlternativaB.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblAlternativaB.setText("Alternativa B:");

        txtAlternativaB.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblAlternativaC.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblAlternativaC.setText("Alternativa C:");

        lblAlternativaD.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblAlternativaD.setText("Alternativa D:");

        txtAlternativaC.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtAlternativaD.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblNivel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblNivel.setText("Nível da questão  ");

        cmbNivel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Médio", "Difícil" }));
        cmbNivel.addActionListener(this::cmbNivelActionPerformed);

        cmbRespostaCorreta.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cmbRespostaCorreta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));

        lblRespostaCorreta.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblRespostaCorreta.setText("Resposta Correta");

        btnVoltar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(39, 51, 54));
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        lblImagem.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblImagem.setText("Imagem:");

        btnSelecionarImagem.setText("Selecionar imagem");
        btnSelecionarImagem.addActionListener(this::btnSelecionarImagemActionPerformed);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Dica:");

        javax.swing.GroupLayout jpnPrincipalLayout = new javax.swing.GroupLayout(jpnPrincipal);
        jpnPrincipal.setLayout(jpnPrincipalLayout);
        jpnPrincipalLayout.setHorizontalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipalLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlTopo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnSelecionarImagem)
                            .addGroup(jpnPrincipalLayout.createSequentialGroup()
                                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRespostaCorreta)
                                    .addComponent(lblAlternativaB)
                                    .addComponent(lblImagem)
                                    .addComponent(cmbRespostaCorreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNivel)
                                    .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(btnSalvarPergunta)
                                .addGap(30, 30, 30)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(lblAlternativaC, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAlternativaA, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAlternativaB, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAlternativaD, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAlternativaC, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAlternativaD, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAlternativaA, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnPrincipalLayout.setVerticalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipalLayout.createSequentialGroup()
                .addComponent(jpnlTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDica, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionarImagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAlternativaA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlternativaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlternativaB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlternativaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlternativaC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlternativaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlternativaD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlternativaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvarPergunta)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jpnPrincipalLayout.createSequentialGroup()
                        .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRespostaCorreta)
                            .addComponent(lblNivel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbRespostaCorreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jpnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jpnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPerguntaActionPerformed
try {
    String enunciado = txtEnunciado.getText();
    String imagem = caminhoImagem;
    String alternativaA = txtAlternativaA.getText();
    String alternativaB = txtAlternativaB.getText();
    String alternativaC = txtAlternativaC.getText();
    String alternativaD = txtAlternativaD.getText();
    String respostaCorreta = cmbRespostaCorreta.getSelectedItem().toString();
    String nivel = cmbNivel.getSelectedItem().toString();
    String dica = txtDica.getText();

    if (enunciado.isEmpty() || alternativaA.isEmpty() || alternativaB.isEmpty()
            || alternativaC.isEmpty() || alternativaD.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios.");
        return;
    }

    Pergunta pergunta = new Pergunta();
    pergunta.setEnunciado(enunciado);
    pergunta.setImagem(imagem);
    pergunta.setAlternativaA(alternativaA);
    pergunta.setAlternativaB(alternativaB);
    pergunta.setAlternativaC(alternativaC);
    pergunta.setAlternativaD(alternativaD);
    pergunta.setRespostaCorreta(respostaCorreta);
    
    pergunta.setDica(dica);
    pergunta.setNivel(nivel);

    DAO dao = new DAO();
    dao.cadastrarPergunta(pergunta);

    javax.swing.JOptionPane.showMessageDialog(this, "Pergunta cadastrada com sucesso!");

    MinhasPerguntas tela = new MinhasPerguntas();
    tela.setVisible(true);
    this.dispose();

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro ao cadastrar pergunta.");
    e.printStackTrace();
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarPerguntaActionPerformed

    private void cmbNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNivelActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
MinhasPerguntas tela = new MinhasPerguntas();
tela.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSelecionarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarImagemActionPerformed
javax.swing.JFileChooser seletor = new javax.swing.JFileChooser();

int resultado = seletor.showOpenDialog(this);

if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
    java.io.File arquivo = seletor.getSelectedFile();
    caminhoImagem = arquivo.getAbsolutePath();

    javax.swing.JOptionPane.showMessageDialog(this, "Imagem selecionada com sucesso!");
} // TODO add your handling code here:
    }//GEN-LAST:event_btnSelecionarImagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaQuestaoProfessor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarPergunta;
    private javax.swing.JButton btnSelecionarImagem;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbNivel;
    private javax.swing.JComboBox<String> cmbRespostaCorreta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jpnPrincipal;
    private javax.swing.JPanel jpnlTopo;
    private javax.swing.JLabel lblAlternativaA;
    private javax.swing.JLabel lblAlternativaB;
    private javax.swing.JLabel lblAlternativaC;
    private javax.swing.JLabel lblAlternativaD;
    private javax.swing.JLabel lblEnunciado;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblRespostaCorreta;
    private javax.swing.JTextField txtAlternativaA;
    private javax.swing.JTextField txtAlternativaB;
    private javax.swing.JTextField txtAlternativaC;
    private javax.swing.JTextField txtAlternativaD;
    private javax.swing.JTextField txtDica;
    private javax.swing.JTextField txtEnunciado;
    // End of variables declaration//GEN-END:variables
}
