/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Leonardo
 */
public class TelaErro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaErro.class.getName());
    private TelaAlunoQuestao telaQuiz;
    /**
     * Creates new form TelaErro
     */
    public TelaErro() {
    initComponents();
    setLocationRelativeTo(null);
    setResizable(false);
}

public TelaErro(TelaAlunoQuestao telaQuiz) {
    initComponents();
    this.telaQuiz = telaQuiz;

    setLocationRelativeTo(null);
    setResizable(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblErro = new javax.swing.JLabel();
        lblMensagemErro = new javax.swing.JLabel();
        btnProximaQuestao = new javax.swing.JButton();
        lblTituloRespostaCorreta = new javax.swing.JLabel();
        lblRespostaCorreta = new javax.swing.JLabel();
        lblTituloSuaResposta = new javax.swing.JLabel();
        lblSuaResposta = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPONTUACAOATUAL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO LAB QUIZ.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO CPS.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo etec.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        lblErro.setBackground(new java.awt.Color(255, 255, 255));
        lblErro.setFont(new java.awt.Font("Verdana", 1, 44)); // NOI18N
        lblErro.setForeground(new java.awt.Color(178, 0, 0));
        lblErro.setText("ERROU!");

        lblMensagemErro.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblMensagemErro.setText("Você não ganhou pontos nesta questão.");

        btnProximaQuestao.setBackground(new java.awt.Color(39, 51, 54));
        btnProximaQuestao.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        btnProximaQuestao.setForeground(new java.awt.Color(255, 255, 255));
        btnProximaQuestao.setText("Próxima questão");
        btnProximaQuestao.addActionListener(this::btnProximaQuestaoActionPerformed);

        lblTituloRespostaCorreta.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTituloRespostaCorreta.setText("Resposta correta:");

        lblRespostaCorreta.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblRespostaCorreta.setText("ALTERNATIVA A ");
        lblRespostaCorreta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 102)));

        lblTituloSuaResposta.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTituloSuaResposta.setText("Sua resposta:");

        lblSuaResposta.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblSuaResposta.setText("ALTERNATIVA C");
        lblSuaResposta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel10.setText("+0 PONTOS");

        jPONTUACAOATUAL.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPONTUACAOATUAL.setForeground(new java.awt.Color(39, 51, 54));
        jPONTUACAOATUAL.setText("Pontuação atual: 0 pontos");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ERRO.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErro)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloRespostaCorreta)
                            .addComponent(lblRespostaCorreta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuaResposta)
                            .addComponent(lblTituloSuaResposta)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMensagemErro)
                        .addGap(24, 24, 24)))
                .addGap(108, 108, 108))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnProximaQuestao))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPONTUACAOATUAL))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErro)
                .addGap(18, 18, 18)
                .addComponent(lblMensagemErro)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloRespostaCorreta)
                    .addComponent(lblTituloSuaResposta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSuaResposta)
                    .addComponent(lblRespostaCorreta))
                .addGap(18, 18, 18)
                .addComponent(btnProximaQuestao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPONTUACAOATUAL)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProximaQuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximaQuestaoActionPerformed
if (telaQuiz != null) {
    telaQuiz.continuarDepoisDoFeedback();
}

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnProximaQuestaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaErro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProximaQuestao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jPONTUACAOATUAL;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblMensagemErro;
    private javax.swing.JLabel lblRespostaCorreta;
    private javax.swing.JLabel lblSuaResposta;
    private javax.swing.JLabel lblTituloRespostaCorreta;
    private javax.swing.JLabel lblTituloSuaResposta;
    // End of variables declaration//GEN-END:variables
}
